<a href="https://colab.research.google.com/github/akashmewara144/YBI-INTERNSHIP-/blob/main/Copy_of_Women_dress_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 # import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# import data
cloth = pd.read_csv('https://github.com/YBIFoundation/ProjectHub-MachineLearning/raw/main/Women%20Clothing%20E-Commerce%20Review.csv')

In [ ]:
cloth.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [ ]:
cloth.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [ ]:
cloth.describe()

Clothing ID           Age        Rating   Recommended  \
count  23486.000000  23486.000000  23486.000000  23486.000000   
mean     918.118709     43.198544      4.196032      0.822362   
std      203.298980     12.279544      1.110031      0.382216   
min        0.000000     18.000000      1.000000      0.000000   
25%      861.000000     34.000000      4.000000      1.000000   
50%      936.000000     41.000000      5.000000      1.000000   
75%     1078.000000     52.000000      5.000000      1.000000   
max     1205.000000     99.000000      5.000000      1.000000   

       Positive Feedback  
count       23486.000000  
mean            2.535936  
std             5.702202  
min             0.000000  
25%             0.000000  
50%             1.000000  
75%             3.000000  
max           122.000000

In [ ]:
cloth.shape

(23486, 10)

In [ ]:
# missing values
cloth.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
cloth[cloth['Review']==""]=np.NaN

In [ ]:
cloth['Review'].fillna("No Review",inplace=True)

In [ ]:
cloth.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
cloth['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

In [ ]:
# Define y and X
cloth.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [ ]:
y=cloth['Rating']

In [ ]:
x=cloth['Review']

In [ ]:
cloth['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

In [ ]:
# train test split
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_test,y_train = train_test_split(x,y,train_size = 0.7,stratify=y,random_state=2529)

In [ ]:
x_train.shape,x_test.shape,y_test.shape,y_train.shape

((16440,), (7046,), (16440,), (7046,))

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
x_train=cv.fit_transform(x_train)

In [ ]:
x_test=cv.fit_transform(x_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model=MultinomialNB()

In [ ]:
from sklearn.utils import resample

# Resample the training set to match the size of the test set
x_train = resample(x_train, replace=True, n_samples=x_test.shape[0])

In [ ]:
from sklearn.utils import resample

# Resample the test set to match the size of the training set
x_test = resample(x_test, replace=True, n_samples=x_train.shape[0])

In [ ]:
model.fit(x_train,y_train)

MultinomialNB()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array([3, 4, 3, ..., 3, 2, 5])

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
y_test = y_test[:y_pred.shape[0]]

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[  27   25   37   44  107]
 [  46   47   61   67  233]
 [ 115   90  111  152  390]
 [ 163  169  194  252  745]
 [ 431  493  470  662 1915]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.03      0.11      0.05       240
           2       0.06      0.10      0.07       454
           3       0.13      0.13      0.13       858
           4       0.21      0.17      0.19      1523
           5       0.56      0.48      0.52      3971

    accuracy                           0.33      7046
   macro avg       0.20      0.20      0.19      7046
weighted avg       0.38      0.33      0.36      7046

